spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ballers_club}
spring.datasource.username=${DATABASE_USERNAME:ballers_club}
spring.datasource.password=${DATABASE_PASSWORD:ballers_club}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.h2.console.enabled=false
server.servlet.session.cookie.secure=${COOKIE_SECURE:true}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
spring.web.resources.cache.period=365d
ballers-club.admin-usernames=${BALLERS_CLUB_ADMIN_USERNAMES:Azzuri}
