package dk.gameday.ballersclub.service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.DefaultApplicationArguments;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;

class PollVoteSchemaMigratorTests {

    @Test
    void preservesExistingVotesWhenAddingAwardTrackingColumns() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:poll-vote-migration;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table poll_votes (
                    id bigint generated by default as identity primary key,
                    poll_id bigint not null,
                    option_id bigint not null,
                    username varchar(80) not null,
                    submitted_at timestamp not null
                )
                """);
        jdbcTemplate.update(
                "insert into poll_votes (poll_id, option_id, username, submitted_at) values (1, 102, 'Azzuri', timestamp '2026-07-02 12:00:00')"
        );
        jdbcTemplate.update(
                "insert into poll_votes (poll_id, option_id, username, submitted_at) values (4, 406, 'Late', timestamp '2026-07-03 12:00:00')"
        );
        jdbcTemplate.update(
                "insert into poll_votes (poll_id, option_id, username, submitted_at) values (4, 406, 'Azzuri', timestamp '2026-07-02 12:00:00')"
        );
        jdbcTemplate.update(
                "insert into poll_votes (poll_id, option_id, username, submitted_at) values (7, 701, 'Hyzz', timestamp '2026-07-03 12:00:00')"
        );

        new PollVoteSchemaMigrator(jdbcTemplate).run(new DefaultApplicationArguments());

        Integer votes = jdbcTemplate.queryForObject("select count(*) from poll_votes", Integer.class);
        Long originalOptionId = jdbcTemplate.queryForObject(
                "select original_option_id from poll_votes where username = 'Azzuri' and poll_id = 1",
                Long.class
        );
        Boolean changed = jdbcTemplate.queryForObject(
                "select changed_after_quarter_final from poll_votes where username = 'Azzuri' and poll_id = 1",
                Boolean.class
        );
        Boolean oldVoteBeforeReopen = jdbcTemplate.queryForObject(
                "select original_vote_before_reopen from poll_votes where username = 'Azzuri' and poll_id = 1",
                Boolean.class
        );
        Boolean lateVoteBeforeReopen = jdbcTemplate.queryForObject(
                "select original_vote_before_reopen from poll_votes where username = 'Late'",
                Boolean.class
        );
        Long azzuriGoldenGloveOption = jdbcTemplate.queryForObject(
                "select option_id from poll_votes where username = 'Azzuri' and poll_id = 4",
                Long.class
        );
        Long azzuriGoldenGloveOriginalOption = jdbcTemplate.queryForObject(
                "select original_option_id from poll_votes where username = 'Azzuri' and poll_id = 4",
                Long.class
        );
        Boolean azzuriGoldenGloveChanged = jdbcTemplate.queryForObject(
                "select changed_after_quarter_final from poll_votes where username = 'Azzuri' and poll_id = 4",
                Boolean.class
        );
        Integer appliedFixes = jdbcTemplate.queryForObject(
                "select count(*) from data_fixes where id = 'restore-azzuri-golden-glove-emiliano-martinez'",
                Integer.class
        );
        Integer hyzzPlayerOfTournamentVotes = jdbcTemplate.queryForObject(
                "select count(*) from poll_votes where username = 'Hyzz' and poll_id = 7",
                Integer.class
        );
        Integer hyzzFixes = jdbcTemplate.queryForObject(
                "select count(*) from data_fixes where id = 'reopen-hyzz-player-of-tournament'",
                Integer.class
        );

        assertThat(votes).isEqualTo(3);
        assertThat(originalOptionId).isEqualTo(102L);
        assertThat(changed).isFalse();
        assertThat(oldVoteBeforeReopen).isTrue();
        assertThat(lateVoteBeforeReopen).isFalse();
        assertThat(azzuriGoldenGloveOption).isEqualTo(407L);
        assertThat(azzuriGoldenGloveOriginalOption).isEqualTo(407L);
        assertThat(azzuriGoldenGloveChanged).isFalse();
        assertThat(appliedFixes).isEqualTo(1);
        assertThat(hyzzPlayerOfTournamentVotes).isZero();
        assertThat(hyzzFixes).isEqualTo(1);
    }
}
