name: Build and deploy JAR app to Azure Web App - copa-mundial-arena

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Java version
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: "17"
        


      - name: Build with Maven
        run: mvn -B -f GameDay/ballers-club/pom.xml clean test package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: GameDay/ballers-club/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
      
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: java-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0E754D012FE34E1DACA2250C722BA34E }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EAAAFBE14F95445C92FB2DD359C88968 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E5D18304F344199A50B041D62B5491A }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: copa-mundial-arena
        package: "*.jar"
